### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined when starting api

### ISSUE THREAD

**Issue by karawitan** [portah/librarian#5]
Hello,

  I almost succeeded to setup librarian (api and frontend).
When I launch the api using:

`MONGO_URL=mongodb://admin:XXXXX@my_mongo_server:27017/librarian meteor --port 3030 --settings private/settings.json --raw-logs|./node_modules/bunyan/bin/bunyan -L`

I get
```

[[[[[ ~/librarian/api ]]]]]

=> Started proxy.
=> Meteor 2.1 is available. Update this project with 'meteor update'.
=> Started your app.

=> App running at: http://localhost:3030/
(node:13097) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
/home/kalou/librarian/api/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read property 'startsWith' of undefined
    at imports/modules/publishers.ts:43:35
    at FilterSubscriber._next (/home/kalou/librarian/api/node_modules/rxjs/internal/operators/filter.js:45:37)
    at FilterSubscriber.Subscriber.next (/home/kalou/librarian/api/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Array.<anonymous> (imports/modules/publishers.ts:38:37)
    at Command.Data [as cb] (/home/kalou/librarian/api/node_modules/osmosis/lib/commands/data.js:17:17)
    at Command.start (/home/kalou/librarian/api/node_modules/osmosis/lib/Command.js:159:21)
    at /home/kalou/librarian/api/node_modules/osmosis/lib/Command.js:166:18
    at dataDone (/home/kalou/librarian/api/node_modules/osmosis/lib/commands/set.js:97:17)
    at Command.cb (/home/kalou/librarian/api/node_modules/osmosis/lib/commands/set.js:140:17)
    at Command.start (/home/kalou/librarian/api/node_modules/osmosis/lib/Command.js:159:21)
    at /home/kalou/librarian/api/node_modules/osmosis/lib/Command.js:163:18
    at Command.Find [as cb] (/home/kalou/librarian/api/node_modules/osmosis/lib/commands/find.js:54:9)
    at Command.start (/home/kalou/librarian/api/node_modules/osmosis/lib/Command.js:159:21)
    at /home/kalou/librarian/api/node_modules/osmosis/lib/Command.js:166:18
    at /home/kalou/librarian/api/node_modules/osmosis/lib/commands/get.js:36:25
    at /home/kalou/librarian/api/node_modules/osmosis/lib/Command.js:396:17
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

Is there anything I should do to get around this issue ?

**Comment by portah** [comment]
I'll try my best to reproduce it, hopefully tomorrow

**Comment by portah** [comment]
Okey I confirm I have the same issue. Either osmosis lib has changed or sub library. You can either return observable of []. Or just comment out the use of that function. I'll check later what was changed in that lib

**Comment by portah** [comment]
Or maybe wikipage has changed. So I did a small fix `      filter((_: any) => !!_ && !!_.title && !_.title.startsWith('List')),
` already pushed

**Comment by karawitan** [comment]
Very good, thank you, this issue is now fixed, I can see the contents of "Folders" now. 
Another issue appear later on, I'll open another issue to track it down
